"""InitDB

Revision ID: 61d9fc4c598f
Revises: 
Create Date: 2025-12-14 11:33:57.531458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d9fc4c598f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_from_app', sa.String(length=64), nullable=False),
    sa.Column('event_source', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_url', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('target_name', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=False),
    sa.Column('target_message_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_event_from_app'), 'notifications', ['event_from_app'], unique=False)
    op.create_index(op.f('ix_notifications_event_source'), 'notifications', ['event_source'], unique=False)
    op.create_index(op.f('ix_notifications_event_type'), 'notifications', ['event_type'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_target_id'), 'notifications', ['target_id'], unique=False)
    op.create_index(op.f('ix_notifications_target_name'), 'notifications', ['target_name'], unique=False)
    op.create_index(op.f('ix_notifications_target_type'), 'notifications', ['target_type'], unique=False)
    op.create_table('tg_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_name', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_groups_tg_id'), 'tg_groups', ['tg_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_auth_type', sa.String(length=100), nullable=False),
    sa.Column('last_auth_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vk_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('vk_name', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vk_groups_vk_id'), 'vk_groups', ['vk_id'], unique=True)
    op.create_table('vk_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('comments', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vk_id', 'type', name='uq_vk_id_type')
    )
    op.create_table('vk_longpoll_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_ts', sa.BigInteger(), nullable=False),
    sa.Column('vk_group_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vk_group_id'], ['vk_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vk_group_id')
    )
    op.create_table('vk_order_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('moderator_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['moderator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vk_order_packages_moderator_user_id'), 'vk_order_packages', ['moderator_user_id'], unique=False)
    op.create_table('vk_orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('vk_group_id', sa.Integer(), nullable=True),
    sa.Column('vk_user_id', sa.BigInteger(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('moderator_user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('count_ordered', sa.BigInteger(), nullable=False),
    sa.Column('count_completed', sa.BigInteger(), nullable=False),
    sa.Column('order_price', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['vk_order_packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vk_group_id'], ['vk_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vk_user_id'], ['vk_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vk_orders_moderator_user_id'), 'vk_orders', ['moderator_user_id'], unique=False)
    op.create_index(op.f('ix_vk_orders_package_id'), 'vk_orders', ['package_id'], unique=False)
    op.create_index(op.f('ix_vk_orders_vk_group_id'), 'vk_orders', ['vk_group_id'], unique=False)
    op.create_index(op.f('ix_vk_orders_vk_user_id'), 'vk_orders', ['vk_user_id'], unique=False)
    op.create_table('vk_gorod_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('vk_group_id', sa.Integer(), nullable=True),
    sa.Column('vk_user_id', sa.BigInteger(), nullable=False),
    sa.Column('vk_order_id', sa.BigInteger(), nullable=True),
    sa.Column('moderator_user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('category', sa.String(length=15), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('comment', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('vk_attachments', sa.JSON(), nullable=False),
    sa.Column('cashed_attachments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vk_group_id'], ['vk_groups.id'], ),
    sa.ForeignKeyConstraint(['vk_order_id'], ['vk_orders.id'], ),
    sa.ForeignKeyConstraint(['vk_user_id'], ['vk_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vk_gorod_post_moderator_user_id'), 'vk_gorod_post', ['moderator_user_id'], unique=False)
    op.create_index(op.f('ix_vk_gorod_post_vk_group_id'), 'vk_gorod_post', ['vk_group_id'], unique=False)
    op.create_index(op.f('ix_vk_gorod_post_vk_id'), 'vk_gorod_post', ['vk_id'], unique=True)
    op.create_index(op.f('ix_vk_gorod_post_vk_order_id'), 'vk_gorod_post', ['vk_order_id'], unique=False)
    op.create_index(op.f('ix_vk_gorod_post_vk_user_id'), 'vk_gorod_post', ['vk_user_id'], unique=False)
    op.create_table('vk_mamochki_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('vk_group_id', sa.Integer(), nullable=True),
    sa.Column('vk_user_id', sa.BigInteger(), nullable=False),
    sa.Column('vk_order_id', sa.BigInteger(), nullable=True),
    sa.Column('moderator_user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('category', sa.String(length=15), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('comment', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('vk_attachments', sa.JSON(), nullable=False),
    sa.Column('cashed_attachments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vk_group_id'], ['vk_groups.id'], ),
    sa.ForeignKeyConstraint(['vk_order_id'], ['vk_orders.id'], ),
    sa.ForeignKeyConstraint(['vk_user_id'], ['vk_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vk_mamochki_post_moderator_user_id'), 'vk_mamochki_post', ['moderator_user_id'], unique=False)
    op.create_index(op.f('ix_vk_mamochki_post_vk_group_id'), 'vk_mamochki_post', ['vk_group_id'], unique=False)
    op.create_index(op.f('ix_vk_mamochki_post_vk_id'), 'vk_mamochki_post', ['vk_id'], unique=True)
    op.create_index(op.f('ix_vk_mamochki_post_vk_order_id'), 'vk_mamochki_post', ['vk_order_id'], unique=False)
    op.create_index(op.f('ix_vk_mamochki_post_vk_user_id'), 'vk_mamochki_post', ['vk_user_id'], unique=False)
    op.create_table('vk_obyavlenie_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('vk_group_id', sa.Integer(), nullable=True),
    sa.Column('vk_user_id', sa.BigInteger(), nullable=False),
    sa.Column('vk_order_id', sa.BigInteger(), nullable=True),
    sa.Column('moderator_user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('category', sa.String(length=15), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('comment', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('vk_attachments', sa.JSON(), nullable=False),
    sa.Column('cashed_attachments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vk_group_id'], ['vk_groups.id'], ),
    sa.ForeignKeyConstraint(['vk_order_id'], ['vk_orders.id'], ),
    sa.ForeignKeyConstraint(['vk_user_id'], ['vk_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vk_obyavlenie_post_moderator_user_id'), 'vk_obyavlenie_post', ['moderator_user_id'], unique=False)
    op.create_index(op.f('ix_vk_obyavlenie_post_vk_group_id'), 'vk_obyavlenie_post', ['vk_group_id'], unique=False)
    op.create_index(op.f('ix_vk_obyavlenie_post_vk_id'), 'vk_obyavlenie_post', ['vk_id'], unique=True)
    op.create_index(op.f('ix_vk_obyavlenie_post_vk_order_id'), 'vk_obyavlenie_post', ['vk_order_id'], unique=False)
    op.create_index(op.f('ix_vk_obyavlenie_post_vk_user_id'), 'vk_obyavlenie_post', ['vk_user_id'], unique=False)
    op.create_table('vk_poteryashka_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('vk_group_id', sa.Integer(), nullable=True),
    sa.Column('vk_user_id', sa.BigInteger(), nullable=False),
    sa.Column('vk_order_id', sa.BigInteger(), nullable=True),
    sa.Column('moderator_user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('category', sa.String(length=15), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('comment', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('vk_attachments', sa.JSON(), nullable=False),
    sa.Column('cashed_attachments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vk_group_id'], ['vk_groups.id'], ),
    sa.ForeignKeyConstraint(['vk_order_id'], ['vk_orders.id'], ),
    sa.ForeignKeyConstraint(['vk_user_id'], ['vk_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vk_poteryashka_post_moderator_user_id'), 'vk_poteryashka_post', ['moderator_user_id'], unique=False)
    op.create_index(op.f('ix_vk_poteryashka_post_vk_group_id'), 'vk_poteryashka_post', ['vk_group_id'], unique=False)
    op.create_index(op.f('ix_vk_poteryashka_post_vk_id'), 'vk_poteryashka_post', ['vk_id'], unique=True)
    op.create_index(op.f('ix_vk_poteryashka_post_vk_order_id'), 'vk_poteryashka_post', ['vk_order_id'], unique=False)
    op.create_index(op.f('ix_vk_poteryashka_post_vk_user_id'), 'vk_poteryashka_post', ['vk_user_id'], unique=False)
    op.create_table('vk_rabota_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('vk_group_id', sa.Integer(), nullable=True),
    sa.Column('vk_user_id', sa.BigInteger(), nullable=False),
    sa.Column('vk_order_id', sa.BigInteger(), nullable=True),
    sa.Column('moderator_user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('category', sa.String(length=15), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('comment', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('vk_attachments', sa.JSON(), nullable=False),
    sa.Column('cashed_attachments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vk_group_id'], ['vk_groups.id'], ),
    sa.ForeignKeyConstraint(['vk_order_id'], ['vk_orders.id'], ),
    sa.ForeignKeyConstraint(['vk_user_id'], ['vk_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vk_rabota_post_moderator_user_id'), 'vk_rabota_post', ['moderator_user_id'], unique=False)
    op.create_index(op.f('ix_vk_rabota_post_vk_group_id'), 'vk_rabota_post', ['vk_group_id'], unique=False)
    op.create_index(op.f('ix_vk_rabota_post_vk_id'), 'vk_rabota_post', ['vk_id'], unique=True)
    op.create_index(op.f('ix_vk_rabota_post_vk_order_id'), 'vk_rabota_post', ['vk_order_id'], unique=False)
    op.create_index(op.f('ix_vk_rabota_post_vk_user_id'), 'vk_rabota_post', ['vk_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vk_rabota_post_vk_user_id'), table_name='vk_rabota_post')
    op.drop_index(op.f('ix_vk_rabota_post_vk_order_id'), table_name='vk_rabota_post')
    op.drop_index(op.f('ix_vk_rabota_post_vk_id'), table_name='vk_rabota_post')
    op.drop_index(op.f('ix_vk_rabota_post_vk_group_id'), table_name='vk_rabota_post')
    op.drop_index(op.f('ix_vk_rabota_post_moderator_user_id'), table_name='vk_rabota_post')
    op.drop_table('vk_rabota_post')
    op.drop_index(op.f('ix_vk_poteryashka_post_vk_user_id'), table_name='vk_poteryashka_post')
    op.drop_index(op.f('ix_vk_poteryashka_post_vk_order_id'), table_name='vk_poteryashka_post')
    op.drop_index(op.f('ix_vk_poteryashka_post_vk_id'), table_name='vk_poteryashka_post')
    op.drop_index(op.f('ix_vk_poteryashka_post_vk_group_id'), table_name='vk_poteryashka_post')
    op.drop_index(op.f('ix_vk_poteryashka_post_moderator_user_id'), table_name='vk_poteryashka_post')
    op.drop_table('vk_poteryashka_post')
    op.drop_index(op.f('ix_vk_obyavlenie_post_vk_user_id'), table_name='vk_obyavlenie_post')
    op.drop_index(op.f('ix_vk_obyavlenie_post_vk_order_id'), table_name='vk_obyavlenie_post')
    op.drop_index(op.f('ix_vk_obyavlenie_post_vk_id'), table_name='vk_obyavlenie_post')
    op.drop_index(op.f('ix_vk_obyavlenie_post_vk_group_id'), table_name='vk_obyavlenie_post')
    op.drop_index(op.f('ix_vk_obyavlenie_post_moderator_user_id'), table_name='vk_obyavlenie_post')
    op.drop_table('vk_obyavlenie_post')
    op.drop_index(op.f('ix_vk_mamochki_post_vk_user_id'), table_name='vk_mamochki_post')
    op.drop_index(op.f('ix_vk_mamochki_post_vk_order_id'), table_name='vk_mamochki_post')
    op.drop_index(op.f('ix_vk_mamochki_post_vk_id'), table_name='vk_mamochki_post')
    op.drop_index(op.f('ix_vk_mamochki_post_vk_group_id'), table_name='vk_mamochki_post')
    op.drop_index(op.f('ix_vk_mamochki_post_moderator_user_id'), table_name='vk_mamochki_post')
    op.drop_table('vk_mamochki_post')
    op.drop_index(op.f('ix_vk_gorod_post_vk_user_id'), table_name='vk_gorod_post')
    op.drop_index(op.f('ix_vk_gorod_post_vk_order_id'), table_name='vk_gorod_post')
    op.drop_index(op.f('ix_vk_gorod_post_vk_id'), table_name='vk_gorod_post')
    op.drop_index(op.f('ix_vk_gorod_post_vk_group_id'), table_name='vk_gorod_post')
    op.drop_index(op.f('ix_vk_gorod_post_moderator_user_id'), table_name='vk_gorod_post')
    op.drop_table('vk_gorod_post')
    op.drop_index(op.f('ix_vk_orders_vk_user_id'), table_name='vk_orders')
    op.drop_index(op.f('ix_vk_orders_vk_group_id'), table_name='vk_orders')
    op.drop_index(op.f('ix_vk_orders_package_id'), table_name='vk_orders')
    op.drop_index(op.f('ix_vk_orders_moderator_user_id'), table_name='vk_orders')
    op.drop_table('vk_orders')
    op.drop_index(op.f('ix_vk_order_packages_moderator_user_id'), table_name='vk_order_packages')
    op.drop_table('vk_order_packages')
    op.drop_table('vk_longpoll_config')
    op.drop_table('vk_users')
    op.drop_index(op.f('ix_vk_groups_vk_id'), table_name='vk_groups')
    op.drop_table('vk_groups')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tg_groups_tg_id'), table_name='tg_groups')
    op.drop_table('tg_groups')
    op.drop_index(op.f('ix_notifications_target_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_target_name'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_target_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_source'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_from_app'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
